title: ensembles_simu_france_2023
ignore_regionals: true
my_club: SPORTING CLUB MOUANS SARTOUX GYMNASTIQUE RYTHMIQUE
events:
  - title: PACA
    ids: 14342
  - title: Auvergne - Rhone Alpes
    ids: 14510,14509
  - title: Bourgogne
    ids: 14844,14845
  - title: Bretagne
    ids: 14862
  - title: Centre - Val de Loire
    ids: 14599
  - title: Corse
    ids: 14477
  - title: Grand Est
    ids: 14459,14460
  - title: Guadeloupe
    ids: 14771
  - title: Hauts-de-France
    ids: 14789,14916
  - title: Ile-de-France
    ids: 14661,14586
  - title: Martinique
    ids: 14908
  - title: Normandie
    ids: 13890
  - title: Nouvelle-Aquitaine
    ids: 13775,13776
  - title: Occitanie
    ids: 14905
  - title: Pays de la Loire
    ids: 14221
# derniers resultats : https://resultats.ffgym.fr/derniers
